import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/network/api_exception.dart';
import '../../data/repositories/seller_repository.dart';
import '../../providers/api_provider.dart';
import '../../core/widgets/store_app_bar.dart';

final adminSellerRepositoryProvider=Provider<SellerRepository>((ref)=>SellerRepository(ref.watch(apiClientProvider)));
class AdminSellersPage extends ConsumerStatefulWidget{const AdminSellersPage({super.key});@override ConsumerState<AdminSellersPage> createState()=>_AdminSellersPageState();}
class _AdminSellersPageState extends ConsumerState<AdminSellersPage>{List<Map<String,dynamic>> _sellers=[];bool _loading=true;String?_error;@override void initState(){super.initState();_load();}Future<void> _load()async{setState((){_loading=true;_error=null;});try{_sellers=await ref.read(adminSellerRepositoryProvider).getAdminSellers();}on ApiException catch(e){_error=e.message;}catch(_){_error='خطا در دریافت فروشنده‌ها';}finally{if(mounted)setState(()=>_loading=false);}}Future<void> _approve(int id)async=>_action(()=>ref.read(adminSellerRepositoryProvider).approveSeller(id));Future<void> _suspend(int id)async=>_action(()=>ref.read(adminSellerRepositoryProvider).suspendSeller(id));Future<void> _reject(int id)async{final controller=TextEditingController();final reason=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('رد درخواست فروشندگی'),content:TextField(controller:controller,maxLines:4,decoration:const InputDecoration(labelText:'دلیل رد',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()=>Navigator.pop(context,controller.text.trim()),child:const Text('رد درخواست'))]));controller.dispose();if(reason==null||reason.isEmpty)return;await _action(()=>ref.read(adminSellerRepositoryProvider).rejectSeller(id,reason));}Future<void> _action(Future<void> Function() action)async{try{await action();if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('عملیات با موفقیت انجام شد')));await _load();}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}}String _status(String? value)=>switch(value){ 'approved'=>'تأیید شده','rejected'=>'رد/تعلیق شده',_=>'در انتظار تأیید'};
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:StoreAppBar(title:'مدیریت فروشندگان',actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh),tooltip:'به‌روزرسانی')]),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Text(_error!)):_sellers.isEmpty?const Center(child:Text('درخواستی برای فروشندگی وجود ندارد')):RefreshIndicator(onRefresh:_load,child:ListView.builder(padding:const EdgeInsets.all(12),itemCount:_sellers.length,itemBuilder:(_,index)=>_sellerCard(_sellers[index])))));
Widget _sellerCard(Map<String,dynamic> seller){final id=int.tryParse('${seller['id']}');final status=seller['status']?.toString();final storeName=seller['store_name']?.toString()??'فروشگاه بدون نام';final user=seller['user'];final email=user is Map?user['email']?.toString():null;return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[const CircleAvatar(child:Icon(Icons.storefront)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(storeName,style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold)),if(email!=null)Text(email),Text('وضعیت: ${_status(status)}')]))]),if(seller['description']!=null&&'${seller['description']}'.isNotEmpty)...[const SizedBox(height:10),Text('${seller['description']}')],if(id!=null&&status!='approved')...[const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>_approve(id),icon:const Icon(Icons.check),label:const Text('تأیید'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>_reject(id),icon:const Icon(Icons.close),label:const Text('رد')))])],if(id!=null&&status=='approved')...[const SizedBox(height:12),OutlinedButton.icon(onPressed:()=>_suspend(id),icon:const Icon(Icons.pause_circle_outline),label:const Text('تعلیق فروشنده'))]])));}
}
