import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/widgets/store_app_bar.dart';
import '../../models/category_model.dart';
import '../../providers/category_provider.dart';
import '../search/search_page.dart';
class CategoriesPage extends ConsumerWidget{const CategoriesPage({super.key});@override Widget build(BuildContext context,WidgetRef ref){final categoriesAsync=ref.watch(categoriesProvider);return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:const StoreAppBar(title:'دسته‌بندی‌ها'),body:categoriesAsync.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(error,_)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('دریافت دسته‌بندی‌ها ناموفق بود.'),const SizedBox(height:12),FilledButton(onPressed:()=>ref.invalidate(categoriesProvider),child:const Text('تلاش مجدد'))]))),data:(categories)=>RefreshIndicator(onRefresh:()=>ref.refresh(categoriesProvider.future),child:categories.isEmpty?ListView(children:const[SizedBox(height:240),Center(child:Text('دسته‌بندی‌ای وجود ندارد'))]:ListView.separated(padding:const EdgeInsets.all(12),itemCount:categories.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(context,index)=>_CategoryTile(category:categories[index])))));}}
class _CategoryTile extends StatelessWidget{const _CategoryTile({required this.category});final CategoryModel category;@override Widget build(BuildContext context)=>Card(child:ExpansionTile(title:Directionality(textDirection:TextDirection.rtl,child:Align(alignment:Alignment.centerRight,child:Text(category.name))),subtitle:category.children.isEmpty?null:Directionality(textDirection:TextDirection.rtl,child:Align(alignment:Alignment.centerRight,child:Text('${category.children.length} زیر‌دسته'))),controlAffinity:ListTileControlAffinity.trailing,children:[_CategoryActionTile(icon:Icons.apps_outlined,title:'همه محصولات',onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>SearchPage(categoryId:category.id,title:'همه محصولات ${category.name}')))),for(final child in category.children)_CategoryActionTile(icon:Icons.chevron_left,title:child.name,onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>SearchPage(categoryId:child.id,title:child.name))))]));}
class _CategoryActionTile extends StatelessWidget{const _CategoryActionTile({required this.icon,required this.title,required this.onTap});final IconData icon;final String title;final VoidCallback onTap;@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.ltr,child:ListTile(contentPadding:const EdgeInsetsDirectional.only(start:16,end:32),leading:Icon(icon),title:Directionality(textDirection:TextDirection.rtl,child:Align(alignment:Alignment.centerLeft,child:Text(title))),onTap:onTap));}
